<?php
/**
 * ConnectInterfaceParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI Access (alpha build)
 *
 * RESTful API for Account Information Services (AIS) and Payment Initiation Services (PIS) (alpha build)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConnectInterfaceParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Container for interface connection parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConnectInterfaceParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConnectInterfaceParams"
     */
    public function testConnectInterfaceParams()
    {
    }

    /**
     * Test attribute "bank_connection_id"
     */
    public function testPropertyBankConnectionId()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "source_interface"
     */
    public function testPropertySourceInterface()
    {
    }

    /**
     * Test attribute "login_credentials"
     */
    public function testPropertyLoginCredentials()
    {
    }

    /**
     * Test attribute "store_secrets"
     */
    public function testPropertyStoreSecrets()
    {
    }

    /**
     * Test attribute "skip_positions_download"
     */
    public function testPropertySkipPositionsDownload()
    {
    }

    /**
     * Test attribute "load_owner_data"
     */
    public function testPropertyLoadOwnerData()
    {
    }

    /**
     * Test attribute "account_references"
     */
    public function testPropertyAccountReferences()
    {
    }

    /**
     * Test attribute "account_types"
     */
    public function testPropertyAccountTypes()
    {
    }

    /**
     * Test attribute "multi_step_authentication"
     */
    public function testPropertyMultiStepAuthentication()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "max_days_for_download"
     */
    public function testPropertyMaxDaysForDownload()
    {
    }
}
