<?php
/**
 * CreateDirectDebitParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI Access (alpha build)
 *
 * RESTful API for Account Information Services (AIS) and Payment Initiation Services (PIS) (alpha build)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateDirectDebitParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Container for direct debit creation parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateDirectDebitParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateDirectDebitParams"
     */
    public function testCreateDirectDebitParams()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "direct_debit_type"
     */
    public function testPropertyDirectDebitType()
    {
    }

    /**
     * Test attribute "sequence_type"
     */
    public function testPropertySequenceType()
    {
    }

    /**
     * Test attribute "direct_debits"
     */
    public function testPropertyDirectDebits()
    {
    }

    /**
     * Test attribute "single_booking"
     */
    public function testPropertySingleBooking()
    {
    }

    /**
     * Test attribute "execution_date"
     */
    public function testPropertyExecutionDate()
    {
    }
}
