<?php
/**
 * MultiStepAuthenticationCallbackTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI Access (alpha build)
 *
 * RESTful API for Account Information Services (AIS) and Payment Initiation Services (PIS) (alpha build)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiStepAuthenticationCallbackTest Class Doc Comment
 *
 * @category    Class
 * @description Container for multi-step authentication data, as passed by the client to finAPI
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiStepAuthenticationCallbackTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiStepAuthenticationCallback"
     */
    public function testMultiStepAuthenticationCallback()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "challenge_response"
     */
    public function testPropertyChallengeResponse()
    {
    }

    /**
     * Test attribute "two_step_procedure_id"
     */
    public function testPropertyTwoStepProcedureId()
    {
    }

    /**
     * Test attribute "redirect_callback"
     */
    public function testPropertyRedirectCallback()
    {
    }

    /**
     * Test attribute "decoupled_callback"
     */
    public function testPropertyDecoupledCallback()
    {
    }
}
